name: ethercrypt
description: A simple password manager

publish_to: 'none'

version: 2.2.1

environment:
  sdk: '>=3.1.0-67.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0
  http: ^1.6.0
  pointycastle: ^4.0.0
  base32: ^2.2.0
  ntp: ^2.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.1.0
  flutter_file_dialog: ^3.0.3
  file_picker: ^11.0.2
  provider: ^6.1.5
  flutter_svg: ^2.3.0
  package_info_plus: ^9.0.1
  pub_semver: ^2.2.0
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/appIcon.svg
    - assets/appIcon48x48.png
    - assets/appIcon96x96.png
    - assets/lightLogo.svg
    - assets/darkLogo.svg
