import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:ethercrypt/engine/api/firebase/firebase_auth.dart';
import 'package:ethercrypt/engine/api/firebase/firestore_codec.dart';
import 'package:ethercrypt/engine/api/firebase/firestore_query.dart';
import 'package:ethercrypt/engine/api/http_client.dart';

class FirestoreApiException implements Exception {
  final String status;
  final String raw;
  final int? statusCode;

  FirestoreApiException(this.status, {required this.raw, this.statusCode});

  @override
  String toString() => 'FirestoreApiException(status: $status, http status: $statusCode)';
}

final class FirestorePrecondition {
  final DateTime? updateTime;
  final bool? exists;

  const FirestorePrecondition._({
    this.updateTime,
    this.exists,
  });

  const FirestorePrecondition.exists(bool exists) : this._(exists: exists);

  const FirestorePrecondition.updateTime(DateTime updateTime) : this._(updateTime: updateTime);
}

class FirestoreDocument {
  final String name;
  final Map<String, dynamic> fields;
  final DateTime createTime;
  final DateTime updateTime;

  const FirestoreDocument({
    required this.name,
    required this.fields,
    required this.createTime,
    required this.updateTime,
  });

  factory FirestoreDocument.fromJson(Map<String, dynamic> json) {
    return FirestoreDocument(
      name: json[FirestoreCodec.docName] as String,
      fields: json[FirestoreCodec.fields] != null ? FirestoreCodec.decodeDocumentFields(json[FirestoreCodec.fields]) : {},
      createTime: DateTime.parse(json[FirestoreCodec.docCreateTime]),
      updateTime: DateTime.parse(json[FirestoreCodec.docUpdateTime]),
    );
  }
}

/// Provides Cloud Firestore document CRUD operations using REST API.
class Firestore {
  static const String _firestoreAuthority = 'firestore.googleapis.com';

  String? _projectId;
  String? _firestoreDocsPath;

  final FirebaseAuth auth;

  Firestore() : auth = FirebaseAuth();

  String? get projectId => _projectId;

  bool get isConfigValid => _projectId != null && _projectId!.trim().isNotEmpty && auth.apiKey != null && auth.apiKey!.trim().isNotEmpty;

  void configure([String? projectId, String? apiKey]) {
    _projectId = projectId;
    _firestoreDocsPath = '/v1/projects/$projectId/databases/(default)/documents';
    auth.apiKey = apiKey;
  }

  /// Creates a new document in a collection with optional intial fields.
  /// Returns the newly created document.
  ///
  /// **Notes**:
  /// - A random document ID is generated by Firestore.
  Future<FirestoreDocument> createDocument(String collectionPath, [Map<String, dynamic> documentFields = const {}]) async {
    final Uri uri = Uri.https(_firestoreAuthority, '$_firestoreDocsPath$collectionPath');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.post(uri, headers: _firestoreApiHeaders(), body: _fieldPayload(documentFields)),
    );
    _throwIfNotSuccessResponse(response);
    return FirestoreDocument.fromJson(json.decode(response.body));
  }

  /// Writes a Firestore document and returns the updated version.
  ///
  /// ### Behavior
  /// - If [updateMask] is not set:
  ///   The document is fully replaced (all existing fields are overwritten).
  ///
  /// - If [updateMask] is provided:
  ///   Only the specified fields are updated, all other fields remain unchanged.
  ///
  /// ### Preconditions
  /// [precondition] controls conditional writes:
  /// - `FirestorePrecondition.updateTime(...)` - write fails if the document changed since that timestamp with status 'FAILED_PRECONDITION'
  /// - `FirestorePrecondition.exists(true)` - write fails if document does not exist with status 'NOT_FOUND'
  /// - `FirestorePrecondition.exists(false)` - write fails if document already exists with status 'ALREADY_EXISTS'.
  Future<FirestoreDocument> writeDocument(
    String docPath,
    Map<String, dynamic> documentFields, {
    List<String>? updateMask,
    FirestorePrecondition? precondition,
  }) async {
    final Uri uri = Uri.https(
      _firestoreAuthority,
      '$_firestoreDocsPath$docPath',
      _buildQueryParams(
        updateMask: updateMask,
        precondition: precondition,
      ),
    );
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.patch(uri, headers: _firestoreApiHeaders(), body: _fieldPayload(documentFields)),
    );
    _throwIfNotSuccessResponse(response);
    return FirestoreDocument.fromJson(json.decode(response.body));
  }

  /// Retrieves a single document.
  ///
  /// **Input**:
  /// - [docPath] is the full path from the database root.
  /// - Optional [fieldMask] filters fields for all returned documents. An empty list only returns the document name.
  Future<FirestoreDocument?> getDocument(String docPath, {List<String>? fieldMask}) async {
    final Uri uri = Uri.https(_firestoreAuthority, '$_firestoreDocsPath$docPath', _buildQueryParams(fieldMask: fieldMask));
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.get(uri, headers: _firestoreApiHeaders()),
    );
    if (response.statusCode == HttpStatus.notFound) return null;
    _throwIfNotSuccessResponse(response);
    return FirestoreDocument.fromJson(json.decode(response.body));
  }

  /// Retrieves all documents from a collection at [collectionPath].
  ///
  /// **Input**:
  /// - [collectionPath] is relative to the database root.
  /// - Optional [fieldMask] filters fields for all returned documents. An empty list only returns the document name.
  ///
  /// **Note**:
  /// - Does not auto-paginate — will only return the first page of results from Firestore.
  Future<List<FirestoreDocument>?> getCollection(String collectionPath, {List<String>? fieldMask}) async {
    final Uri uri = Uri.https(_firestoreAuthority, '$_firestoreDocsPath$collectionPath', _buildQueryParams(fieldMask: fieldMask));
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.get(uri, headers: _firestoreApiHeaders()),
    );
    if (response.statusCode == HttpStatus.notFound) return null;
    _throwIfNotSuccessResponse(response);

    final collection = json.decode(response.body);
    final documents = (collection['documents'] as List<dynamic>?) ?? [];
    return documents.map((e) => FirestoreDocument.fromJson(e)).toList();
  }

  /// Deletes the document at [docPath].
  Future<void> deleteDocument(String docPath) async {
    final Uri uri = Uri.https(_firestoreAuthority, '$_firestoreDocsPath$docPath');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.delete(uri, headers: _firestoreApiHeaders()),
    );
    _throwIfNotSuccessResponse(response);
  }

  /// Retrieves documents which match the criteria.
  Future<List<FirestoreDocument>> query(FirestoreQuery query) async {
    final Uri uri = Uri.https(_firestoreAuthority, '$_firestoreDocsPath${query.collectionParentPath ?? ''}:runQuery');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.post(uri, headers: _firestoreApiHeaders(), body: json.encode(query.toJson())),
    );

    _throwIfNotSuccessResponse(response);

    final List<dynamic> results = json.decode(response.body);
    return results
        .where(
          (e) => e is Map<String, dynamic> && e['document'] != null,
        )
        .map(
          (e) => FirestoreDocument.fromJson(e['document']),
        )
        .toList();
  }

  // ----------- Helpers ------------
  Future<http.Response> _apiRequestWithReAuth(Future<http.Response> Function(http.Client) apiCall) async {
    if (!auth.isUserLoggedIn) {
      throw Exception('Firestore user is not logged in');
    }
    final http.Client httpClient = LoggingHttpClient();

    try {
      http.Response response = await apiCall(httpClient);
      if (response.statusCode == HttpStatus.unauthorized) {
        await auth.loginWithRefreshToken(auth.user!.email, auth.user!.refreshToken);
        response = await apiCall(httpClient);
      }

      return response;
    } finally {
      httpClient.close();
    }
  }

  void _throwIfNotSuccessResponse(http.Response response) {
    if (response.statusCode < 200 || response.statusCode >= 300) {
      dynamic data;
      try {
        // Response may have json formatted error info
        data = json.decode(response.body);
      } catch (_) {}
      throw FirestoreApiException(
        data?['error']?['status'] ?? 'UNKNOWN',
        statusCode: response.statusCode,
        raw: response.body,
      );
    }
  }

  Map<String, String> _firestoreApiHeaders() {
    return {
      HttpHeaders.authorizationHeader: 'Bearer ${auth.user?.idToken}',
      HttpHeaders.contentTypeHeader: ContentType.json.value,
    };
  }

  String _fieldPayload(Map<String, dynamic> documentFields) {
    return json.encode({FirestoreCodec.fields: FirestoreCodec.encodeDocumentFields(documentFields)});
  }

  Map<String, String>? _buildQueryParams({
    Iterable<String>? fieldMask,
    Iterable<String>? updateMask,
    FirestorePrecondition? precondition,
  }) {
    final Map<String, String> query = {};

    if (fieldMask != null) {
      // Note: '__name__' is firestores internal to indicate only to documents full path name to be returned
      query['mask.fieldPaths'] = fieldMask.isEmpty ? '__name__' : fieldMask.join(',');
    }

    if (updateMask != null && updateMask.isNotEmpty) {
      query['updateMask.fieldPaths'] = updateMask.join(',');
    }

    if (precondition != null && precondition.updateTime != null) {
      query['currentDocument.updateTime'] = precondition.updateTime!.toUtc().toIso8601String();
    }

    if (precondition != null && precondition.exists != null) {
      query['currentDocument.exists'] = precondition.exists.toString();
    }

    return query.isEmpty ? null : query;
  }
}
