import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:ethercrypt/engine/api/firebase/firebase_auth.dart';
import 'package:ethercrypt/engine/api/firebase/firestore_codec.dart';
import 'package:ethercrypt/engine/api/firebase/firestore_query.dart';
import 'package:ethercrypt/engine/api/http_client.dart';

class FirestoreApiException implements Exception {
  final int? unexpectedCode;
  final dynamic raw;

  FirestoreApiException({required this.unexpectedCode, required this.raw});

  @override
  String toString() => 'FirestoreApiException(unexpectedCode: $unexpectedCode)';
}

class FirestoreDocument {
  final String name;
  final Map<String, dynamic> fields;
  final DateTime? createTime;
  final DateTime? updateTime;

  const FirestoreDocument({
    required this.name,
    required this.fields,
    this.createTime,
    this.updateTime,
  });

  factory FirestoreDocument.fromJson(Map<String, dynamic> json) {
    return FirestoreDocument(
      name: json[FirestoreCodec.docName] as String,
      fields: json[FirestoreCodec.fields] != null ? FirestoreCodec.decodeDocumentFields(json[FirestoreCodec.fields]) : {},
      createTime: json[FirestoreCodec.docCreateTime] != null ? DateTime.parse(json[FirestoreCodec.docCreateTime]) : null,
      updateTime: json[FirestoreCodec.docUpdateTime] != null ? DateTime.parse(json[FirestoreCodec.docUpdateTime]) : null,
    );
  }
}

/// Provides Cloud Firestore document CRUD operations using REST API.
class Firestore {
  String? _projectId;
  String? _firestoreBasePath;

  final FirebaseAuth auth;

  Firestore() : auth = FirebaseAuth();

  String? get projectId => _projectId;

  bool get isConfigValid => _projectId != null && _projectId!.trim().isNotEmpty && auth.apiKey != null && auth.apiKey!.trim().isNotEmpty;

  void configure([String? projectId, String? apiKey]) {
    _projectId = projectId;
    _firestoreBasePath = 'https://firestore.googleapis.com/v1/projects/$projectId/databases/(default)/documents';
    auth.apiKey = apiKey;
  }

  /// Creates a new document in a collection with optional intial fields.
  /// Returns the newly created document.
  ///
  /// **Notes**:
  /// - A random document ID is generated by Firestore.
  Future<FirestoreDocument> createDocument(String collectionPath, [Map<String, dynamic> documentFields = const {}]) async {
    final Uri uri = Uri.parse('$_firestoreBasePath$collectionPath');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.post(uri, headers: _firestoreApiHeaders(), body: _fieldPayload(documentFields)),
    );
    _throwIfNotSuccessResponse(response);
    return FirestoreDocument.fromJson(json.decode(response.body));
  }

  /// Creates or completely overwrites the document and sets its fields.
  /// Returns the updated / created document.
  ///
  /// **Behavior**:
  /// - If the document exists, all existing fields will be replaced.
  /// - If it doesn't exist, it will be created.
  Future<FirestoreDocument> setDocument(String docPath, Map<String, dynamic> documentFields) async {
    final Uri uri = Uri.parse('$_firestoreBasePath$docPath');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.patch(uri, headers: _firestoreApiHeaders(), body: _fieldPayload(documentFields)),
    );
    _throwIfNotSuccessResponse(response);
    return FirestoreDocument.fromJson(json.decode(response.body));
  }

  /// Retrieves a single document.
  ///
  /// **Input**:
  /// - [docPath] is the full path from the database root.
  /// - Optional [fieldMask] filters which fields are returned.
  Future<FirestoreDocument?> getDocument(String docPath, {List<String>? fieldMask}) async {
    final Uri uri = Uri.parse('$_firestoreBasePath$docPath${_buildFieldMask(fieldMask)}');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.get(uri, headers: _firestoreApiHeaders()),
    );
    if (response.statusCode == HttpStatus.notFound) return null;
    _throwIfNotSuccessResponse(response);
    return FirestoreDocument.fromJson(json.decode(response.body));
  }

  /// Retrieves all documents from a collection at [collectionPath].
  ///
  /// **Input**:
  /// - [collectionPath] is relative to the database root.
  /// - Optional [fieldMask] filters fields for all returned documents. An empty list only returns the document name.
  ///
  /// **Note**:
  /// - Does not auto-paginate — will only return the first page of results from Firestore.
  Future<List<FirestoreDocument>?> getCollection(String collectionPath, {List<String>? fieldMask}) async {
    final Uri uri = Uri.parse('$_firestoreBasePath$collectionPath${_buildFieldMask(fieldMask)}');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.get(uri, headers: _firestoreApiHeaders()),
    );
    if (response.statusCode == HttpStatus.notFound) return null;
    _throwIfNotSuccessResponse(response);

    final collection = json.decode(response.body);
    final documents = (collection['documents'] as List<dynamic>?) ?? [];
    return documents.map((e) => FirestoreDocument.fromJson(e)).toList();
  }

  /// Updates only existing fields in a document specified by [docPath]. Returns the updated document.
  Future<FirestoreDocument> updateDocument(String docPath, Map<String, dynamic> documentFields) async {
    final Uri uri = Uri.parse('$_firestoreBasePath$docPath?updateMask.fieldPaths=${documentFields.keys.join(",")}');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.patch(uri, headers: _firestoreApiHeaders(), body: _fieldPayload(documentFields)),
    );
    _throwIfNotSuccessResponse(response);
    return FirestoreDocument.fromJson(json.decode(response.body));
  }

  /// Deletes the document at [docPath].
  Future<void> deleteDocument(String docPath) async {
    final Uri uri = Uri.parse('$_firestoreBasePath$docPath');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.delete(uri, headers: _firestoreApiHeaders()),
    );
    _throwIfNotSuccessResponse(response);
  }

  /// Retrieves documents which match the criteria.
  Future<List<FirestoreDocument>> query(FirestoreQuery query) async {
    final Uri uri = Uri.parse('$_firestoreBasePath${query.collectionParentPath ?? ''}:runQuery');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.post(uri, headers: _firestoreApiHeaders(), body: json.encode(query.toJson())),
    );

    _throwIfNotSuccessResponse(response);

    final List<dynamic> results = json.decode(response.body);
    return results
        .where(
          (e) => e is Map<String, dynamic> && e['document'] != null,
        )
        .map(
          (e) => FirestoreDocument.fromJson(e['document']),
        )
        .toList();
  }

  // ----------- Helpers ------------
  Future<http.Response> _apiRequestWithReAuth(Future<http.Response> Function(http.Client) apiCall) async {
    if (!auth.isUserLoggedIn) {
      throw Exception('Firestore user is not logged in');
    }
    final http.Client httpClient = LoggingHttpClient();

    try {
      http.Response response = await apiCall(httpClient);
      if (response.statusCode == HttpStatus.unauthorized) {
        await auth.loginWithRefreshToken(auth.user!.email, auth.user!.refreshToken);
        response = await apiCall(httpClient);
      }

      return response;
    } finally {
      httpClient.close();
    }
  }

  void _throwIfNotSuccessResponse(http.Response response) {
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw FirestoreApiException(
        unexpectedCode: response.statusCode,
        raw: response.body,
      );
    }
  }

  Map<String, String> _firestoreApiHeaders() {
    return {
      HttpHeaders.authorizationHeader: 'Bearer ${auth.user?.idToken}',
      HttpHeaders.contentTypeHeader: ContentType.json.value,
    };
  }

  String _fieldPayload(Map<String, dynamic> documentFields) {
    return json.encode({FirestoreCodec.fields: FirestoreCodec.encodeDocumentFields(documentFields)});
  }

  String _buildFieldMask(List<String>? fieldMask) {
    if (fieldMask == null) return '';
    if (fieldMask.isEmpty) return '?mask.fieldPaths=__name__'; // Firestore internal var to indicate only to document id to be returned
    final encoded = fieldMask.map(Uri.encodeQueryComponent).join(',');
    return '?mask.fieldPaths=$encoded';
  }
}
