import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:passwordmanager/engine/api/firebase/firebase_auth.dart';
import 'package:passwordmanager/engine/api/http_client.dart';

class FirestoreApiException implements Exception {
  final int? unexpectedCode;
  final dynamic raw;

  FirestoreApiException({required this.unexpectedCode, required this.raw});

  @override
  String toString() => 'FirestoreApiException(unexpectedCode: $unexpectedCode)';
}

/// Provides Cloud Firestore document CRUD operations using REST API.
class Firestore {
  String? _projectId;
  String? _firestoreBasePath;

  final FirebaseAuth auth;

  Firestore() : auth = FirebaseAuth();

  String? get projectId => _projectId;

  bool get isConfigValid => _projectId != null && _projectId!.trim().isNotEmpty && auth.apiKey != null && auth.apiKey!.trim().isNotEmpty;

  void configure([String? projectId, String? apiKey]) {
    _projectId = projectId;
    _firestoreBasePath = 'https://firestore.googleapis.com/v1/projects/$projectId/databases/(default)/documents';
    auth.apiKey = apiKey;
  }

  /// Creates a new document in a collection with optional intial fields.
  ///
  /// **Output**:
  /// - Returns the document's full resource path:
  ///   `"projects/{projectId}/databases/(default)/documents/{collectionPath}/{docId}"`
  ///
  /// **Notes**:
  /// - A random document ID is generated by Firestore.
  Future<String> createDocument(String collectionPath, Map<String, dynamic> documentFields) async {
    final Uri uri = Uri.parse('$_firestoreBasePath/$collectionPath');
    final String parsedFields = json.encode({'fields': _parseFields(documentFields)});

    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.post(uri, headers: _firestoreApiHeaders(), body: parsedFields),
    );

    final data = json.decode(response.body);
    return data['name'];
  }

  /// Creates or completely overwrites the document and sets its fields.
  ///
  /// **Behavior**:
  /// - If the document exists, all existing fields will be replaced.
  /// - If it doesn't exist, it will be created.
  Future<void> setDocument(String docPath, Map<String, dynamic> documentFields) async {
    final Uri uri = Uri.parse('$_firestoreBasePath/$docPath');
    final String parsedFields = json.encode(_parseFields(documentFields));

    await _apiRequestWithReAuth(
      (client) => client.patch(uri, headers: _firestoreApiHeaders(), body: parsedFields),
    );
  }

  /// Retrieves a single document.
  ///
  /// **Input**:
  /// - [docPath] is the full path from the database root.
  /// - Optional [fieldMask] filters which fields are returned. An empty list only returns the document name.
  ///
  /// **Output**:
  /// - Returns the raw Firestore REST response as a Dart `Map<String, dynamic>`.
  ///   Example structure:
  ///   ```json
  ///   {
  ///     "name": "projects/.../documents/users/userId",
  ///     "fields": {
  ///       "username": {"stringValue": "alice"},
  ///       "age": {"integerValue": "30"}
  ///     },
  ///     "createTime": "...",
  ///     "updateTime": "..."
  ///   }
  ///   ```
  ///
  /// **Note**:
  /// - This does **not** unwrap the `"fields"` map to raw Dart types — caller must handle that.
  Future<Map<String, dynamic>> getDocument(String docPath, {List<String>? fieldMask}) async {
    final Uri uri = Uri.parse('$_firestoreBasePath/$docPath${_buildFieldMask(fieldMask)}');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.get(uri, headers: _firestoreApiHeaders()),
    );

    return json.decode(response.body);
  }

  /// Retrieves all documents from a collection at [collectionPath].
  ///
  /// **Input**:
  /// - [collectionPath] is relative to the database root.
  /// - Optional [fieldMask] filters fields for all returned documents. An empty list only returns the document name.
  ///
  /// **Output**:
  /// - Returns a list of raw Firestore REST document maps, same structure as [getDocument].
  /// - If the collection is empty, returns an empty list.
  ///
  /// **Note**:
  /// - Does not auto-paginate — will only return the first page of results from Firestore.
  Future<List<Map<String, dynamic>>> getCollection(String collectionPath, {List<String>? fieldMask}) async {
    final Uri uri = Uri.parse('$_firestoreBasePath/$collectionPath${_buildFieldMask(fieldMask)}');
    final http.Response response = await _apiRequestWithReAuth(
      (client) => client.get(uri, headers: _firestoreApiHeaders()),
    );
    final data = json.decode(response.body);
    final documents = (data['documents'] as List?) ?? [];
    return documents.cast<Map<String, dynamic>>();
  }

  /// Updates updates existing fields in an existing document specified by [docPath].
  Future<void> updateDocument(String docPath, Map<String, dynamic> data) async {
    if (data.isEmpty) return;

    final Uri uri = Uri.parse('$_firestoreBasePath/$docPath?updateMask.fieldPaths=${data.keys.join(",")}');
    final String parsedFields = json.encode({'fields': _parseFields(data)});
    await _apiRequestWithReAuth(
      (client) => client.patch(uri, headers: _firestoreApiHeaders(), body: parsedFields),
    );
  }

  /// Deletes the document at [docPath].
  Future<void> deleteDocument(String docPath) async {
    final Uri uri = Uri.parse('$_firestoreBasePath/$docPath');
    await _apiRequestWithReAuth(
      (client) => client.delete(uri, headers: _firestoreApiHeaders()),
    );
  }

  // ----------- Helpers ------------
  Future<http.Response> _apiRequestWithReAuth(Future<http.Response> Function(http.Client) apiCall) async {
    if (!auth.isUserLoggedIn) {
      throw Exception('Firestore user is not logged in');
    }
    final http.Client httpClient = LoggingHttpClient();

    try {
      http.Response response = await apiCall(httpClient);
      if (response.statusCode == HttpStatus.unauthorized) {
        await auth.loginWithRefreshToken(auth.user!.email, auth.user!.refreshToken);
        response = await apiCall(httpClient);
      }

      if (response.statusCode != HttpStatus.ok) {
        throw FirestoreApiException(unexpectedCode: response.statusCode, raw: response.body);
      }
      return response;
    } finally {
      httpClient.close();
    }
  }

  Map<String, String> _firestoreApiHeaders() => {
        HttpHeaders.authorizationHeader: 'Bearer ${auth.user?.idToken}',
        HttpHeaders.contentTypeHeader: ContentType.json.value,
      };

  String _buildFieldMask(List<String>? fieldMask) {
    if (fieldMask == null) return '';
    if (fieldMask.isEmpty) return '?mask.fieldPaths=__name__'; // Firestore internal var to indicate only to document id to be returned
    final encoded = fieldMask.map(Uri.encodeQueryComponent).join(',');
    return '?mask.fieldPaths=$encoded';
  }

  /// Converts a plain map to firestores explicit named format
  Map<String, dynamic> _parseFields(Map<String, dynamic> data) {
    return data.map((key, value) => MapEntry(key, _typedValue(value)));
  }

  // Firestores field format
  Map<String, dynamic> _typedValue(dynamic value) {
    if (value is String) return {'stringValue': value};
    if (value is bool) return {'booleanValue': value};
    if (value is int) return {'integerValue': value.toString()};
    if (value is double) return {'doubleValue': value};
    if (value is Map) {
      return {
        'mapValue': {'fields': _parseFields(value as Map<String, dynamic>)}
      };
    }
    if (value is List) {
      return {
        'arrayValue': {'values': value.map(_typedValue).toList()}
      };
    }
    throw Exception('Unsupported Firestore type: ${value.runtimeType}');
  }
}
